### PR TITLE
Add entry for subsonic plugin for upmpdcli

### PR DESCRIPTION
**Pull request by GioF71**
As requested in the [discussion](https://github.com/navidrome/navidrome/discussions/2324). Please let me know if I need to reduce the amount of information or if I need to arrange it differently

### CODE REVIEW

**Comment by deluan** [comment]
Thanks for the PR, but can you make the entry short, like the others? I may change this section in the future to allow more info about the clients, but for now it is a simple list. Something like this would be better:

- [upmpdcli](https://www.lesbonscomptes.com/upmpdcli/index.html) - expose Navidrome as a UPnP/DLNA media library

**Comment by GioF71** [comment]
Corrected as per your request

**Comment by GioF71** [comment]
I was thinking if we can maybe link the discussion? We can stay in one line. The 'problem' with the documentation of upmpdcli is that the subsonic plugin is just a plugin, and there is only a small mention to Navidrome. I would keep the discussion updated with the changes if this is something that can be useful.
Thanks

**Comment by deluan** [comment]
Yeah, linking to the discussion is fine.

**Pull request merged**
