### PR TITLE
add troubleshooting section to document inotify watchers

### PR DESCRIPTION
**Pull request by MoralCode**

### CODE REVIEW

**Review by deluan — CHANGES_REQUESTED** [review]
Thanks @MoralCode, I like the idea of adding a "Troubleshooting" section, but this is not the symptom of hitting the inotify limit. I don't remember now what is the error you get, but if you search for "inotify" in Discord you may find some discussions about this.

**Comment by MoralCode** [comment]
Would it be better to replace the part about the "Compiling..." message with something like "..and are not seeing any changes you make reflected in your localhost copy of the site..."? or were you referring to a different symptom?

**Comment by deluan** [comment]
A completely different symptom. IIRC, it does not even start when the number of max files is too low. I tried to reproduce the issue here, and could not get it. Here is a link to someone reporting this issue in Discord: https://discord.com/channels/671335427726114836/818940805494341683/819997446352142366

**Comment by MoralCode** [comment]
oh okay. I was basing this change on the conversation at https://discord.com/channels/671335427726114836/704303730660737113/826145304138219520 which seemed to be related

**Pull request merged**
