### PR TITLE
add error 404 page

### PR DESCRIPTION
**Pull request by khareyash05**
#67 
added error 404 page

### CODE REVIEW

**Comment by khareyash05** [comment]
@deluan Created a PR have a look!

**Comment by deluan** [comment]
Not sure if I like the animation... Also, it breaks on mobile:

Screenshot_20211120-224100
Screenshot_20211120-224129

**Comment by khareyash05** [comment]
@deluan idk how but I have deployed this page and its perfectly working on mobile version as well
image

**Review by prakhar3062 — APPROVED** [review]

**Comment by deluan** [comment]
Still broken, unfortunately.
Screenshot 2023-03-09 at 12 11 52 PM

At this point, I think it is better to start over. Thanks anyway!

**Pull request closed without merging**
