### PR TITLE
Document DevActivityPanel option

### PR DESCRIPTION
**Pull request by norohind**
It took me some time in first place to figure out such option exists, I hope adding it to documentation is going to save somebody time.

### CODE REVIEW

**Comment by deluan** [comment]
Sorry for missing this. I don't want to start documenting the `Dev*` config options, as they are temporary and used mainly for testing features. 

The issue about the UI freezing that `DevActivityPanel` "solves" is actually a workaround, that should be fixed in the new UI I'm working on. I'm ok with adding this workaround to a Troubleshooting section, or even the FAQ, but don't think it makes sense to add it to the list of documented config options.

**Comment by norohind** [comment]
I like the idea to add this at least to troubleshooting section. I will repurpose this PR for it in following couple of days then.

**Comment by deluan** [comment]
I don't think this is required anymore. Version 0.53.0 Introduced throttling to the Activity Panel that virtually eliminated the need to disable it.

@norohind, is this still an issue for you?

**Comment by norohind** [comment]
The problem seems to be gone. Thank you.

**Pull request closed without merging**
